# put goscons in the python path
import os.path
import sys
sys.path.insert(0, os.path.dirname(sys.path[0]))
from goscons import GoEnvironment
env = GoEnvironment()
env.GoPackages('src')
env.GoPackage('foo/src/pkg5')
